<?php

return [
    'towns' => [
        'Agno',
        'Aguilar',
        'Alaminos City',
        'Alcala',
        'Anda',
        'Asingan',
        'Balungao',
        'Bani',
        'Basista',
        'Bautista',
        'Bayambang',
        'Binalonan',
        'Binmaley',
        'Bolinao',
        'Bugallon',
        'Burgos',
        'Calasiao',
        'Dagupan City',
        'Dasol',
        'Infanta',
        'Labrador',
        'Laoac',
        'Lingayen',
        'Mabini',
        'Malasiqui',
        'Manaoag',
        'Mangaldan',
        'Mangatarem',
        'Mapandan',
        'Natividad',
        'Pozorrubio',
        'Rosales',
        'San Carlos City',
        'San Fabian',
        'San Jacinto',
        'San Manuel',
        'San Nicolas',
        'San Quintin',
        'Santa Barbara',
        'Santa Maria',
        'Santo Tomas',
        'Sison',
        'Sual',
        'Tayug',
        'Umingan',
        'Urbiztondo',
        'Urdaneta City',
        'Villasis',
    ],
];
